/* eslint-disable react-hooks/set-state-in-effect -- hydrate the pre-auth draft after the browser is available. */
'use client';

import Link from 'next/link';
import { useEffect, useState } from 'react';
import { ArrowRight, Check } from 'lucide-react';
import { defaultMvpState, directionLabels, readMvpState, saveMvpState, trackMvp, type MessageFrequency, type MvpState, type VoiceStyle } from '@/lib/mvp';

const voices: { id: VoiceStyle; text: string }[] = [
  { id: 'grounded', text: 'La duda puede estar aquí sin borrar lo que ya pensabas.' },
  { id: 'warm', text: 'Que haya aparecido la duda no significa que tu criterio desapareció con ella.' },
  { id: 'direct', text: 'Antes de buscar otra respuesta, vuelve un momento a la que ya tenías.' },
];
type Step = 'change' | 'context' | 'language' | 'voice' | 'messages' | 'email' | 'ready';

export default function OnboardingPage() {
  const [state, setState] = useState<MvpState>(defaultMvpState);
  const [step, setStep] = useState<Step>('change');
  const [saving, setSaving] = useState(false);
  useEffect(() => setState(readMvpState()), []);
  const patch = (next: Partial<MvpState>) => setState(current => ({ ...current, ...next }));
  const save = () => { saveMvpState(state); trackMvp('onboarding_step_completed', { step }); };
  const next = () => { save(); setStep(step === 'change' ? 'context' : step === 'context' ? 'language' : step === 'language' ? 'voice' : step === 'voice' ? 'messages' : step === 'messages' ? 'email' : 'ready'); };
  const name = state.firstName || 'Laura';
  const submitDraft = async () => { setSaving(true); await fetch('/api/onboarding-draft', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ first_name: name, email: state.email, direction_key: state.directionKey, direction_text: state.directionText || state.desiredChangeOriginal, voice_style: state.voiceStyle, message_frequency: state.messageFrequency, message_time_1: state.messageFrequency ? state.messageTime1 : null, message_time_2: state.messageFrequency === 2 ? state.messageTime2 : null, timezone: state.timezone, whatsapp_enabled: false, desired_change_original: state.desiredChangeOriginal, current_context_original: state.currentContextOriginal, preferred_language: state.preferredLanguage?.join(', ') || null }) }); setSaving(false); next(); };
  return <main className="min-h-dvh bg-[var(--bg)] px-5 py-8 text-[var(--text-primary)] [font-family:var(--font-body)] sm:px-8"><div className="mx-auto max-w-[720px]"><header className="flex items-center justify-between"><Link href="/descubre" className="font-semibold">NIA</Link></header>
    {step === 'change' && <section className="pt-20"><h1 className="text-[clamp(39px,7vw,78px)] leading-[.94] [font-family:var(--font-display)]">¿Qué te gustaría cambiar, mejorar o vivir de una manera diferente en esta etapa?</h1><textarea autoFocus value={state.desiredChangeOriginal || ''} onChange={event => patch({ desiredChangeOriginal: event.target.value })} className="mt-10 min-h-32 w-full resize-y border-b-2 border-black/20 bg-transparent p-2 text-[20px] outline-none" /><button type="button" disabled={!state.desiredChangeOriginal?.trim()} onClick={next} className="mt-8 inline-flex min-h-[52px] items-center gap-2 rounded-[var(--radius-button)] bg-[var(--accent)] px-6 font-semibold text-[var(--bg)]">Seguir desde aquí <ArrowRight size={17}/></button></section>}
    {step === 'context' && <section className="pt-20"><h1 className="text-[clamp(39px,7vw,78px)] leading-[.94] [font-family:var(--font-display)]">¿En qué situaciones notas que más te cuesta actuar como realmente quieres?</h1><textarea autoFocus value={state.currentContextOriginal || ''} onChange={event => patch({ currentContextOriginal: event.target.value })} className="mt-10 min-h-32 w-full resize-y border-b-2 border-black/20 bg-transparent p-2 text-[20px] outline-none" /><button type="button" disabled={!state.currentContextOriginal?.trim()} onClick={next} className="mt-8 inline-flex min-h-[52px] items-center gap-2 rounded-[var(--radius-button)] bg-[var(--accent)] px-6 font-semibold text-[var(--bg)]">Continuar <ArrowRight size={17}/></button></section>}
    {step === 'language' && <section className="pt-20"><h1 className="text-[clamp(39px,7vw,78px)] leading-[.94] [font-family:var(--font-display)]">¿Qué tendría que decirte NIA para que sintieras que realmente te está hablando a ti?</h1><textarea value={state.preferredLanguage?.join(' ') || ''} onChange={event => patch({ preferredLanguage: event.target.value ? [event.target.value] : [] })} className="mt-10 min-h-32 w-full resize-y border-b-2 border-black/20 bg-transparent p-2 text-[20px] outline-none" /><p className="mt-4 text-[14px] text-[var(--text-secondary)]">Puedes dejarlo vacío.</p><button type="button" onClick={next} className="mt-8 inline-flex min-h-[52px] items-center gap-2 rounded-[var(--radius-button)] bg-[var(--accent)] px-6 font-semibold text-[var(--bg)]">Seguir <ArrowRight size={17}/></button></section>}
    {step === 'voice' && <section className="pt-20"><h1 className="text-[clamp(39px,7vw,78px)] leading-[.94] [font-family:var(--font-display)]">¿Cuál se parece más a cómo quieres que te hable NIA?</h1><div className="mt-10 space-y-3">{voices.map(voice => <button key={voice.id} type="button" onClick={() => patch({ voiceStyle: voice.id })} className={`flex min-h-24 w-full gap-4 rounded-[var(--radius-card)] border p-5 text-left text-[17px] ${state.voiceStyle === voice.id ? 'border-[var(--accent)] bg-[var(--text-primary)] text-[var(--bg)]' : 'border-black/15 bg-[var(--surface)]'}`}><span className="mt-1 size-5 shrink-0 rounded-full border">{state.voiceStyle === voice.id && <Check size={13}/>}</span>{voice.text}</button>)}</div><button type="button" onClick={next} className="mt-8 inline-flex min-h-[52px] items-center gap-2 rounded-[var(--radius-button)] bg-[var(--accent)] px-6 font-semibold text-[var(--bg)]">Elegir esta forma de hablar <ArrowRight size={17}/></button></section>}
    {step === 'messages' && <section className="pt-20"><h1 className="text-[clamp(39px,7vw,76px)] leading-[.94] [font-family:var(--font-display)]">¿Quieres que NIA también llegue a ti durante el día?</h1><div className="mt-10 grid gap-3">{([{ value: 1, label: 'Sí, una vez al día.', note: 'Recomendado' }, { value: 2, label: 'Sí, dos veces al día.', note: 'Máximo para empezar' }, { value: 0, label: 'Prefiero verla solo dentro de NIA.', note: 'Sin mensajes externos' }] as { value: MessageFrequency; label: string; note: string }[]).map(option => <button key={option.value} type="button" onClick={() => patch({ messageFrequency: option.value, messageTime1: option.value === 0 ? '' : state.messageTime1 || '08:00', messageTime2: option.value === 2 ? state.messageTime2 || '18:00' : undefined, whatsappEnabled: false })} className={`rounded-[var(--radius-card)] border p-5 text-left ${state.messageFrequency === option.value ? 'border-[var(--accent)] bg-[var(--text-primary)] text-[var(--bg)]' : 'border-black/15 bg-[var(--surface)]'}`}><span className="block text-[17px] font-semibold">{option.label}</span><span className="mt-1 block text-[12px] opacity-70">{option.note}</span></button>)}</div>{state.messageFrequency > 0 && <div className="mt-6 grid gap-4 sm:grid-cols-2"><label htmlFor="onboarding-time-1" className="text-[12px] font-bold tracking-[.15em] text-[var(--text-tertiary)]">{state.messageFrequency === 2 ? 'Primer mensaje' : '¿A qué hora quieres recibirla?'}<input id="onboarding-time-1" type="time" value={state.messageTime1 || '08:00'} onChange={event => patch({ messageTime1: event.target.value })} className="mt-2 block h-12 border-b-2 border-black/20 bg-transparent text-[18px]" /></label>{state.messageFrequency === 2 && <label htmlFor="onboarding-time-2" className="text-[12px] font-bold tracking-[.15em] text-[var(--text-tertiary)]">Segundo mensaje<input id="onboarding-time-2" type="time" value={state.messageTime2 || '18:00'} onChange={event => patch({ messageTime2: event.target.value })} className="mt-2 block h-12 border-b-2 border-black/20 bg-transparent text-[18px]" /></label>}</div>}<p className="mt-6 text-[14px] text-[var(--text-secondary)]">Podrás cambiar esto después desde NIA.</p><button type="button" onClick={next} className="mt-8 inline-flex min-h-[52px] items-center gap-2 rounded-[var(--radius-button)] bg-[var(--accent)] px-6 font-semibold text-[var(--bg)]">Elegir mis mensajes <ArrowRight size={17}/></button></section>}
    {step === 'email' && <section className="pt-20"><h1 className="text-[clamp(39px,7vw,76px)] leading-[.94] [font-family:var(--font-display)]">¿Dónde quieres recibir tu acceso a NIA?</h1><label htmlFor="email" className="mt-10 block text-[12px] font-bold tracking-[.15em] text-[var(--text-tertiary)]">Correo electrónico</label><input id="email" type="email" value={state.email} onChange={event => patch({ email: event.target.value })} className="mt-3 h-14 w-full border-b-2 border-black/20 bg-transparent text-[22px]" /><button type="button" disabled={!state.email.includes('@') || saving} onClick={submitDraft} className="mt-8 inline-flex min-h-[52px] rounded-[var(--radius-button)] bg-[var(--accent)] px-6 font-semibold text-[var(--bg)]">Ver mi configuración <ArrowRight size={17}/></button></section>}
    {step === 'ready' && <section className="pt-20"><h1 className="text-[clamp(39px,7vw,76px)] leading-[.94] [font-family:var(--font-display)]">{name}, tu NIA está preparada para empezar contigo.</h1><div className="mt-10 space-y-3"><div className="bg-[var(--surface)] p-6"><p className="text-[22px] [font-family:var(--font-display)]">{state.desiredChangeOriginal}</p><p className="mt-4 text-[15px] text-[var(--text-secondary)]">{state.currentContextOriginal}</p></div><div className="bg-[var(--surface)] p-6"><p className="text-[18px]">{directionLabels[state.directionKey]}</p><p className="mt-3 text-[18px]">{state.messageFrequency === 0 ? 'Solo dentro de NIA.' : state.messageFrequency === 1 ? `1 vez al día · ${state.messageTime1}` : `2 veces al día · ${state.messageTime1} y ${state.messageTime2}`}</p></div></div><p className="mt-8 text-[16px] text-[var(--text-secondary)]">Cuando entres, no tendrás que configurar todo otra vez.</p><Link href="/paywall" onClick={() => { saveMvpState({ ...state, onboardingComplete: true }); trackMvp('prepaywall_ready'); }} className="mt-8 inline-flex min-h-[52px] items-center gap-2 rounded-[var(--radius-button)] bg-[var(--accent)] px-6 font-semibold text-[var(--bg)]">Activar mi NIA <ArrowRight size={17}/></Link></section>}
  </div></main>;
}
