/* eslint-disable react-hooks/set-state-in-effect -- load the authenticated product state after browser session hydration. */
'use client';
import { useEffect, useState } from 'react';
import { MvpShell } from '@/components/app/MvpShell';
import { trackMvp } from '@/lib/mvp';

export default function AppHomePage() {
  const [profile, setProfile] = useState<Record<string, unknown> | null>(null); const [connection, setConnection] = useState<{ status: string; phone_number?: string | null } | null>(null); const [latest, setLatest] = useState<{ content?: string } | null>(null); const [error, setError] = useState(false);
  useEffect(() => { trackMvp('app_home_viewed'); Promise.all([fetch('/api/profile').then(async r => { if (!r.ok) throw new Error('profile'); return r.json(); }), fetch('/api/whatsapp/connection').then(r => r.json()), fetch('/api/interactions').then(r => r.ok ? r.json() : null)]).then(([profilePayload, connectionPayload, interactionsPayload]) => { setProfile(profilePayload?.profile ?? null); setConnection(connectionPayload?.connection ?? { status: connectionPayload?.status ?? 'not_connected' }); setLatest(interactionsPayload?.interactions?.[0] ?? null); }).catch(() => setError(true)); }, []);
  const firstName = typeof profile?.first_name === 'string' ? profile.first_name : ''; const direction = typeof profile?.desired_change_original === 'string' ? profile.desired_change_original : typeof profile?.direction_text === 'string' ? profile.direction_text : ''; const time = typeof profile?.message_time_1 === 'string' ? profile.message_time_1 : ''; const connected = connection?.status === 'connected';
  return <MvpShell title="Hoy"><section className="pt-8"><p className="text-[13px] font-semibold uppercase tracking-[.14em] text-[var(--accent)]">HOY</p><h1 className="mt-5 max-w-[650px] text-[clamp(39px,7vw,76px)] leading-[.94] tracking-[-.06em] [font-family:var(--font-display)]">{firstName ? `Hola, ${firstName}.` : 'NIA está lista para empezar contigo.'}</h1>{error && <p role="alert" className="mt-6 border-l-2 border-red-700 pl-4 text-[14px] text-red-800">No pudimos cargar el estado de NIA. Vuelve a intentarlo.</p>}<div className="mt-10 grid gap-3 sm:grid-cols-3"><article className="rounded-[var(--radius-card)] border border-black/10 bg-[var(--surface)] p-5"><p className="text-[11px] font-bold uppercase tracking-[.12em] text-[var(--text-tertiary)]">Estás trabajando en</p><p className="mt-4 text-[21px] leading-[1.08] [font-family:var(--font-display)]">{direction || 'Aún no has definido una dirección.'}</p></article><article className="rounded-[var(--radius-card)] border border-black/10 bg-[var(--surface)] p-5"><p className="text-[11px] font-bold uppercase tracking-[.12em] text-[var(--text-tertiary)]">Próximo mensaje</p><p className="mt-4 text-[21px] leading-[1.08] [font-family:var(--font-display)]">{time || 'Configúralo en Tú.'}</p></article><article className="rounded-[var(--radius-card)] border border-black/10 bg-[var(--surface)] p-5"><p className="text-[11px] font-bold uppercase tracking-[.12em] text-[var(--text-tertiary)]">WhatsApp</p><p className="mt-4 text-[21px] leading-[1.08] [font-family:var(--font-display)]">{connected ? 'Conectado' : 'Aún no conectado'}</p></article></div>{latest?.content && <section className="mt-10 border-l-2 border-[var(--accent)] pl-5"><p className="text-[11px] font-bold uppercase tracking-[.12em] text-[var(--text-tertiary)]">Último mensaje disponible</p><p className="mt-4 max-w-[700px] text-[28px] leading-[1.02] [font-family:var(--font-display)]">{latest.content}</p></section>}</section></MvpShell>;
}
