'use client';

import { AlertTriangle, CheckCircle2, Clock3, Database, UsersRound } from 'lucide-react';
import { useCallback, useEffect, useState } from 'react';
import { AdminHeader, EmptyState, ErrorState, LoadingState, MetricCard, PeriodFilter, RefreshButton, SectionHeading } from './ui';

type Stat = { average: number; min: number; max: number } | null;
type Dashboard = {
  period: { label: string };
  users: { total: number; active: number; new: number; onboardingCompleted: number; activityToday: number; activeSubscriptions: number | null };
  interventions: { requests: number; completed: number; approved: number; delivered: number; failed: number; noApproved: number; approvalRate: number | null };
  generation: { attempts: number; candidatesGenerated: number; candidatesApproved: number; candidatesRejected: number; technicalRetries: number; qualityRetries: number };
  errors: { total: number; breakdown: { code: string; operation: string; provider: string; count: number; last_occurred_at: string }[] };
  performance: { execution: Stat; provider: { operation: string; average: number; min: number; max: number }[] };
  engine: { executions: number; approved: number; noApproved: number; failed: number; rejectionLayers: Record<string, number>; executionHealth: { date: string; executions: number; approved: number; noApproved: number; failed: number }[] };
  feedback: { received: number; learningSignals: number };
  providerUsage: { calls: number; inputTokens: number; outputTokens: number; totalTokens: number; latency: Stat; providers: { provider: string; model: string; calls: number; input_tokens: number; output_tokens: number; total_tokens: number; latency: Stat; errors: number }[] };
  events: { event_type: string; count: number }[];
  editorial: { topics: [string, number][]; formats: [string, number][]; depths: [string, number][] };
  available: string[];
  unavailable: string[];
  costs: { total: number; averagePerExecution: number | null; averagePerIntervention: number | null; averagePerActiveUser: number | null; byOperation: { operation: string; calls: number; total_cost: number; percentage: number; unavailable: number }[]; byModel: { provider: string; model: string; calls: number; input_tokens: number; output_tokens: number; total_cost: number; unavailable: number }[]; trend: { date: string; total_cost: number }[]; unavailableCalls: number } | { status: string; reason: string };
};

const number = (value: number | null | undefined) => value === null || value === undefined ? 'NOT AVAILABLE' : new Intl.NumberFormat('en-US').format(value);
const percent = (value: number | null) => value === null ? 'NOT AVAILABLE' : `${Math.round(value * 100)}%`;
const date = (value: string) => new Date(value).toLocaleString('en-GB', { dateStyle: 'short', timeStyle: 'short' });
const shortDate = (value: string) => new Date(`${value}T00:00:00Z`).toLocaleDateString('en-GB', { day: '2-digit', month: 'short' });
const stat = (value: Stat, suffix = 'ms') => value ? `${number(value.average)} ${suffix}` : 'NOT AVAILABLE';
const money = (value: number | null | undefined) => value === null || value === undefined ? 'NOT AVAILABLE' : `$${value.toFixed(value > 0 && value < 0.01 ? 6 : 4)}`;

function MiniTable({ children }: { children: React.ReactNode }) { return <div className="overflow-x-auto rounded-[16px] border border-black/10 bg-[var(--surface)]"><table className="w-full min-w-[620px] text-left text-[13px]">{children}</table></div>; }
function TableHead({ children }: { children: React.ReactNode }) { return <thead className="border-b border-black/10 bg-[var(--bg)] text-[10px] uppercase tracking-[.12em] text-[var(--text-tertiary)]"><tr>{children}</tr></thead>; }
function Cell({ children, className = '', title, colSpan }: { children: React.ReactNode; className?: string; title?: string; colSpan?: number }) { return <td title={title} colSpan={colSpan} className={`px-4 py-3 ${className}`}>{children}</td>; }
function EmptyMetric({ detail = 'Fuente de datos todavía no instrumentada.' }: { detail?: string }) { return <span title={detail} className="text-[13px] font-semibold text-[var(--text-tertiary)]">NOT AVAILABLE</span>; }
function CostSection({ costs }: { costs: Dashboard['costs'] }) {
  if (!('total' in costs)) return <section><SectionHeading title="Cost ledger" /><EmptyState title="AI cost NOT AVAILABLE" detail={costs.reason} /></section>;
  return <section><SectionHeading title="Cost ledger" /><p className="mb-4 text-[12px] text-[var(--text-secondary)]">AI spend only. Infrastructure, WhatsApp y billing no están incluidos.</p><div className="space-y-5"><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><MetricCard label="AI spend" value={money(costs.total)} accent /><MetricCard label="Average / execution" value={money(costs.averagePerExecution)} /><MetricCard label="Average / intervention" value={money(costs.averagePerIntervention)} /><MetricCard label="Average / active user" value={money(costs.averagePerActiveUser)} /></div><div className="grid gap-8 xl:grid-cols-2"><div><SectionHeading title="Cost by operation" /><MiniTable><TableHead><th className="px-4 py-3">Operation</th><th className="px-4 py-3">Calls</th><th className="px-4 py-3">Cost</th><th className="px-4 py-3">Share</th></TableHead><tbody className="divide-y divide-black/10">{costs.byOperation.map(row => <tr key={row.operation}><Cell className="capitalize">{row.operation.replaceAll('_', ' ')}</Cell><Cell>{row.calls}</Cell><Cell>{money(row.total_cost)}</Cell><Cell>{Math.round(row.percentage * 100)}%</Cell></tr>)}</tbody></MiniTable></div><div><SectionHeading title="Cost by model" /><MiniTable><TableHead><th className="px-4 py-3">Provider / model</th><th className="px-4 py-3">Calls</th><th className="px-4 py-3">Tokens</th><th className="px-4 py-3">Cost</th></TableHead><tbody className="divide-y divide-black/10">{costs.byModel.map(row => <tr key={`${row.provider}:${row.model}`}><Cell><strong>{row.provider}</strong><span className="mt-1 block text-[11px] text-[var(--text-secondary)]">{row.model}</span></Cell><Cell>{row.calls}</Cell><Cell>{number(row.input_tokens + row.output_tokens)}</Cell><Cell>{money(row.total_cost)}</Cell></tr>)}</tbody></MiniTable></div></div><div><SectionHeading title="Cost trend" />{costs.trend.length ? <MiniTable><TableHead><th className="px-4 py-3">Date</th><th className="px-4 py-3">AI spend</th></TableHead><tbody className="divide-y divide-black/10">{costs.trend.map(row => <tr key={row.date}><Cell>{row.date}</Cell><Cell>{money(row.total_cost)}</Cell></tr>)}</tbody></MiniTable> : <EmptyMetric detail="No calculable cost in this period." />}</div>{costs.unavailableCalls > 0 && <p className="text-[12px] text-[var(--text-secondary)]">{costs.unavailableCalls} llamadas no tienen costo calculable y no se cuentan como cero.</p>}</div></section>;
}

export default function AdminDashboardPage() {
  const [period, setPeriod] = useState('7d');
  const [from, setFrom] = useState('');
  const [to, setTo] = useState('');
  const [data, setData] = useState<Dashboard | null>(null);
  const [error, setError] = useState('');
  const [loading, setLoading] = useState(true);
  const load = useCallback(() => {
    setLoading(true); setError('');
    const query = new URLSearchParams({ period });
    if (period === 'custom' && from && to) { query.set('date_from', from); query.set('date_to', to); }
    fetch(`/api/admin/dashboard?${query}`).then(async response => { const body = await response.json(); if (!response.ok) throw new Error(body.error); return body as Dashboard; }).then(setData).catch(() => setError('No pudimos cargar NIA Control. Verifica tu acceso administrativo y la disponibilidad de las tablas operativas.')).finally(() => setLoading(false));
  }, [period, from, to]);
  // Initial data fetch synchronizes this client view with the server API.
  // eslint-disable-next-line react-hooks/set-state-in-effect
  useEffect(() => { load(); }, [load]);

  return <div>
    <AdminHeader eyebrow="NIA Control / Dashboard" title="Lo que está pasando ahora." description={data ? `Periodo: ${data.period.label}. Una lectura operacional basada en ejecuciones y eventos persistidos.` : 'Operación, motor y salud del producto en una sola lectura.'} actions={<><RefreshButton onClick={load} /><PeriodFilter value={period} onChange={value => { setPeriod(value); if (value !== 'custom') { setFrom(''); setTo(''); } }} from={from} to={to} onDatesChange={(nextFrom, nextTo) => { setFrom(nextFrom); setTo(nextTo); }} /></>} />
    {error ? <ErrorState message={error} /> : loading && !data ? <LoadingState /> : data ? <div className="space-y-8">
      <section><SectionHeading title="Operational pulse" /><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><MetricCard label="Users" value={number(data.users.active)} note={`${number(data.users.total)} total · ${number(data.users.new)} new`} accent /><MetricCard label="Executions" value={number(data.interventions.completed + data.interventions.noApproved + data.interventions.failed)} note={`${number(data.interventions.requests)} intervention requests`} /><MetricCard label="Delivered" value={number(data.interventions.delivered)} note={`${number(data.interventions.approved)} approved`} /><MetricCard label="No approved" value={number(data.interventions.noApproved)} note="Not an infrastructure failure" /></div><p className="mt-3 text-[12px] text-[var(--text-secondary)]">Onboarding completed: {number(data.users.onboardingCompleted)} · Active subscriptions: {data.users.activeSubscriptions === null ? 'NOT AVAILABLE' : number(data.users.activeSubscriptions)}</p></section>
      <section><SectionHeading title="Quality and load" /><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><MetricCard label="Candidates" value={number(data.generation.candidatesGenerated)} note={`${number(data.generation.candidatesRejected)} rejected · ${number(data.generation.candidatesApproved)} approved`} /><MetricCard label="Approval" value={percent(data.interventions.approvalRate)} note="Approved / completed executions" accent /><MetricCard label="Retries" value={number(data.generation.technicalRetries + data.generation.qualityRetries)} note={`${number(data.generation.technicalRetries)} technical · ${number(data.generation.qualityRetries)} quality`} /><MetricCard label="Errors" value={number(data.errors.total)} note={`${number(data.interventions.failed)} failed executions`} /></div></section>
      <section className="rounded-[20px] border border-black/10 bg-[var(--surface)] p-5"><SectionHeading title="Editorial overview" /><div className="grid gap-6 md:grid-cols-3"><div><h3 className="text-[12px] font-semibold uppercase tracking-[.1em] text-[var(--text-tertiary)]">Topics</h3>{data.editorial.topics.length ? data.editorial.topics.slice(0, 8).map(([topic, count]) => <div key={topic} className="mt-2 flex justify-between text-[13px]"><span className="truncate">{topic}</span><span>{count}</span></div>) : <p className="mt-2 text-[13px] text-[var(--text-secondary)]">Sin metadata editorial.</p>}</div><div><h3 className="text-[12px] font-semibold uppercase tracking-[.1em] text-[var(--text-tertiary)]">Formats</h3>{data.editorial.formats.map(([format, count]) => <div key={format} className="mt-2 flex justify-between text-[13px]"><span>{format.replaceAll('_', ' ')}</span><span>{count}</span></div>)}</div><div><h3 className="text-[12px] font-semibold uppercase tracking-[.1em] text-[var(--text-tertiary)]">Depth</h3>{data.editorial.depths.map(([depth, count]) => <div key={depth} className="mt-2 flex justify-between text-[13px]"><span>{depth}</span><span>{count}</span></div>)}</div></div></section>

      <section><SectionHeading title="Execution health" href="/admin/operations" />{data.engine.executionHealth.length ? <MiniTable><TableHead><th className="px-4 py-3">Date</th><th className="px-4 py-3">Executions</th><th className="px-4 py-3">Approved</th><th className="px-4 py-3">No approved</th><th className="px-4 py-3">Failed</th></TableHead><tbody className="divide-y divide-black/10">{data.engine.executionHealth.map(row => <tr key={row.date}><Cell>{shortDate(row.date)}</Cell><Cell>{row.executions}</Cell><Cell className="text-[#345238]">{row.approved}</Cell><Cell className="text-[#775723]">{row.noApproved}</Cell><Cell className="text-[#813e31]">{row.failed}</Cell></tr>)}</tbody></MiniTable> : <EmptyState title="No execution data" detail="No hay ejecuciones en este periodo." />}</section>

      <div className="grid gap-8 xl:grid-cols-[1fr_1fr]"><section><SectionHeading title="Failure breakdown" href="/admin/errors" />{data.errors.breakdown.length ? <MiniTable><TableHead><th className="px-4 py-3">Code</th><th className="px-4 py-3">Operation</th><th className="px-4 py-3">Provider</th><th className="px-4 py-3">Count</th><th className="px-4 py-3">Last</th></TableHead><tbody className="divide-y divide-black/10">{data.errors.breakdown.map(row => <tr key={`${row.code}:${row.operation}:${row.provider}`}><Cell className="font-mono text-[11px] text-[#813e31]">{row.code}</Cell><Cell>{row.operation}</Cell><Cell>{row.provider}</Cell><Cell>{row.count}</Cell><Cell className="whitespace-nowrap text-[12px] text-[var(--text-secondary)]">{date(row.last_occurred_at)}</Cell></tr>)}</tbody></MiniTable> : <EmptyState title="No recorded errors" detail="No hay fallos técnicos en este periodo." />}</section><section><SectionHeading title="Generation" href="/admin/operations" /><MiniTable><TableHead><th className="px-4 py-3">Metric</th><th className="px-4 py-3">Value</th></TableHead><tbody className="divide-y divide-black/10"><tr><Cell>Attempts</Cell><Cell>{data.generation.attempts}</Cell></tr><tr><Cell>Candidates generated</Cell><Cell>{data.generation.candidatesGenerated}</Cell></tr><tr><Cell>Candidates approved</Cell><Cell>{data.generation.candidatesApproved}</Cell></tr><tr><Cell>Candidates rejected</Cell><Cell>{data.generation.candidatesRejected}</Cell></tr><tr><Cell>Deterministic / semantic / LLM rejection events</Cell><Cell>{number(data.engine.rejectionLayers.deterministic ?? 0)} / {number(data.engine.rejectionLayers.semantic ?? 0)} / {number(data.engine.rejectionLayers.llm ?? 0)}</Cell></tr></tbody></MiniTable></section></div>

      <div className="grid gap-8 xl:grid-cols-[1.25fr_.75fr]"><section><SectionHeading title="Provider usage" /><MiniTable><TableHead><th className="px-4 py-3">Provider / model</th><th className="px-4 py-3">Calls</th><th className="px-4 py-3">Tokens</th><th className="px-4 py-3">Latency</th><th className="px-4 py-3">Errors</th></TableHead><tbody className="divide-y divide-black/10">{data.providerUsage.providers.map(row => <tr key={`${row.provider}:${row.model}`}><Cell><strong>{row.provider}</strong><span className="mt-1 block text-[11px] text-[var(--text-secondary)]">{row.model}</span></Cell><Cell>{row.calls}</Cell><Cell>{number(row.total_tokens)}</Cell><Cell title={row.latency ? `${row.latency.min}–${row.latency.max} ms` : undefined}>{stat(row.latency)}</Cell><Cell className="text-[#813e31]">{row.errors}</Cell></tr>)}{!data.providerUsage.providers.length && <tr><Cell colSpan={5}><EmptyMetric /></Cell></tr>}</tbody></MiniTable><p className="mt-3 text-[12px] text-[var(--text-secondary)]">Input: {number(data.providerUsage.inputTokens)} · Output: {number(data.providerUsage.outputTokens)} · Total: {number(data.providerUsage.totalTokens)} · Average latency: {stat(data.providerUsage.latency)}</p></section><section><SectionHeading title="Performance" /><div className="rounded-[16px] border border-black/10 bg-[var(--surface)] p-5"><div className="grid grid-cols-3 gap-3 text-center"><div><p className="text-[11px] uppercase tracking-[.1em] text-[var(--text-tertiary)]">Execution avg</p><p className="mt-2 text-[21px] [font-family:var(--font-display)]">{stat(data.performance.execution)}</p></div><div><p className="text-[11px] uppercase tracking-[.1em] text-[var(--text-tertiary)]">Min</p><p className="mt-2 text-[21px] [font-family:var(--font-display)]">{data.performance.execution ? `${data.performance.execution.min} ms` : <EmptyMetric />}</p></div><div><p className="text-[11px] uppercase tracking-[.1em] text-[var(--text-tertiary)]">Max</p><p className="mt-2 text-[21px] [font-family:var(--font-display)]">{data.performance.execution ? `${data.performance.execution.max} ms` : <EmptyMetric />}</p></div></div><div className="mt-6 space-y-3 border-t border-black/10 pt-5 text-[13px]">{data.performance.provider.map(row => <div key={row.operation} className="flex items-center justify-between"><span className="capitalize text-[var(--text-secondary)]">{row.operation.replaceAll('_', ' ')}</span><span>{row.average} ms <span className="text-[11px] text-[var(--text-tertiary)]">({row.min}–{row.max})</span></span></div>)}{!data.performance.provider.length && <EmptyMetric />}</div></div></section></div>

      <div className="grid gap-8 xl:grid-cols-[.8fr_1.2fr]"><section><SectionHeading title="Feedback and learning" /><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-1"><MetricCard label="Feedback received" value={number(data.feedback.received)} /><MetricCard label="Learning signals" value={number(data.feedback.learningSignals)} /></div></section><section><SectionHeading title="Events" href="/admin/operations" />{data.events.length ? <MiniTable><TableHead><th className="px-4 py-3">Event</th><th className="px-4 py-3">Count</th></TableHead><tbody className="divide-y divide-black/10">{data.events.map(row => <tr key={row.event_type}><Cell className="font-semibold capitalize">{row.event_type.replaceAll('_', ' ')}</Cell><Cell>{row.count}</Cell></tr>)}</tbody></MiniTable> : <EmptyState title="No events" detail="No hay eventos instrumentados en este periodo." />}</section></div>

      <CostSection costs={data.costs} />

      <section><SectionHeading title="Data availability" /><div className="grid gap-8 md:grid-cols-2"><div className="rounded-[16px] border border-[#9ab39b]/40 bg-[#edf4ec] p-5"><div className="flex items-center gap-2 text-[#345238]"><CheckCircle2 size={17} /><h3 className="font-semibold">Available</h3></div><ul className="mt-4 grid gap-2 text-[13px] text-[#345238]">{data.available.map(item => <li key={item}>✓ {item.replaceAll('_', ' ')}</li>)}</ul></div><div className="rounded-[16px] border border-black/10 bg-[var(--surface)] p-5"><div className="flex items-center gap-2 text-[var(--text-secondary)]"><Database size={17} /><h3 className="font-semibold">Not available yet</h3></div><ul className="mt-4 grid gap-2 text-[13px] text-[var(--text-secondary)]">{data.unavailable.map(item => <li key={item}>— {item}</li>)}</ul><p className="mt-4 text-[12px] text-[var(--text-tertiary)]">La fuente todavía no está instrumentada; no se muestra como cero.</p></div></div></section>

      <section className="grid gap-4 sm:grid-cols-3"><div className="rounded-[16px] border border-black/10 bg-[var(--surface)] p-5"><div className="flex items-center gap-2 text-[var(--text-secondary)]"><UsersRound size={16} /><span className="text-[12px] font-semibold uppercase tracking-[.1em]">Active subscriptions</span></div><p className="mt-4 text-[24px] [font-family:var(--font-display)]">{data.users.activeSubscriptions === null ? <EmptyMetric /> : data.users.activeSubscriptions}</p></div><div className="rounded-[16px] border border-black/10 bg-[var(--surface)] p-5"><div className="flex items-center gap-2 text-[var(--text-secondary)]"><Clock3 size={16} /><span className="text-[12px] font-semibold uppercase tracking-[.1em]">Activity today</span></div><p className="mt-4 text-[24px] [font-family:var(--font-display)]">{number(data.users.activityToday)}</p></div><div className="rounded-[16px] border border-black/10 bg-[var(--surface)] p-5"><div className="flex items-center gap-2 text-[var(--text-secondary)]"><AlertTriangle size={16} /><span className="text-[12px] font-semibold uppercase tracking-[.1em]">Failure count</span></div><p className="mt-4 text-[24px] [font-family:var(--font-display)]">{number(data.errors.total)}</p></div></section>
    </div> : null}
  </div>;
}
