/* eslint-disable react-hooks/set-state-in-effect -- hydrate local preview state after the browser is available. */
'use client';

import { useEffect, useState } from 'react';
import { ArrowLeft, ArrowRight } from 'lucide-react';
import Link from 'next/link';
import { MvpShell } from '@/components/app/MvpShell';
import { contextLabels, defaultMvpState, getIntervention, readMvpState, trackMvp, type ContextKey, type FeedbackType, type MvpState } from '@/lib/mvp';

export default function PuntoPage() {
  const [state, setState] = useState<MvpState>(defaultMvpState); const [context, setContext] = useState<ContextKey | null>(null); const [feedback, setFeedback] = useState<FeedbackType | null>(null);
  useEffect(() => { setState(readMvpState()); }, []);
  return <MvpShell title="Punto NIA"><section className="pt-10">{!context && <><Link href="/app" className="inline-flex items-center gap-2 text-[13px] text-[var(--text-tertiary)]"><ArrowLeft size={15} />Volver a Hoy</Link><p className="mt-12 text-[11px] font-bold uppercase tracking-[0.16em] text-[var(--accent)]">PUNTO NIA</p><h1 className="mt-5 max-w-[680px] text-[clamp(39px,7vw,76px)] font-semibold leading-[0.94] tracking-[-0.06em] [font-family:var(--font-display)]">{state.firstName || 'Laura'}, ¿qué está apareciendo ahora?</h1><div className="mt-10 grid gap-3 sm:grid-cols-2">{(Object.keys(contextLabels) as ContextKey[]).map((key) => <button key={key} type="button" onClick={() => { setContext(key); trackMvp('nia_point_completed', { context: key }); }} className="min-h-16 rounded-[var(--radius-card)] border border-[color-mix(in_oklab,var(--text-primary)_16%,transparent)] bg-[var(--surface)] p-5 text-left text-[16px] font-semibold">{contextLabels[key]}</button>)}</div></>}{context && <><p className="text-[11px] font-bold uppercase tracking-[0.16em] text-[var(--accent)]">UNA INTERVENCIÓN BREVE</p><h1 className="mt-5 max-w-[760px] text-[clamp(35px,6vw,68px)] leading-[0.96] tracking-[-0.05em] [font-family:var(--font-display)]">{getIntervention(state, context, feedback ?? undefined)}</h1><p className="mt-8 max-w-[580px] text-[15px] leading-[1.6] text-[var(--text-secondary)]">No decide por ti. Solo devuelve la dirección que elegiste.</p>{!feedback ? <div className="mt-10 grid gap-3 sm:grid-cols-3"><button type="button" onClick={() => setFeedback('resonates')} className="min-h-24 rounded-[var(--radius-card)] border border-[color-mix(in_oklab,var(--text-primary)_16%,transparent)] p-5 text-left text-[14px] font-semibold">Sí. Esto sí me devuelve a mí.</button><button type="button" onClick={() => setFeedback('needs_grounding')} className="min-h-24 rounded-[var(--radius-card)] border border-[color-mix(in_oklab,var(--text-primary)_16%,transparent)] p-5 text-left text-[14px] font-semibold">Necesito algo más aterrizado.</button><button type="button" onClick={() => setFeedback('different_angle')} className="min-h-24 rounded-[var(--radius-card)] border border-[color-mix(in_oklab,var(--text-primary)_16%,transparent)] p-5 text-left text-[14px] font-semibold">Necesito verlo de otra manera.</button></div> : <div className="mt-10"><p className="border-l-2 border-[var(--accent)] pl-5 text-[18px] text-[var(--text-secondary)]">La próxima intervención podría ajustarse a esta señal. Este Punto NIA termina aquí.</p><Link href="/app" className="mt-8 inline-flex min-h-12 items-center gap-2 rounded-[var(--radius-button)] bg-[var(--accent)] px-5 text-[14px] font-semibold text-[var(--bg)]">Volver a Hoy <ArrowRight size={16} /></Link></div>}</>}</section></MvpShell>;
}
