/* eslint-disable react-hooks/set-state-in-effect */
'use client';
import { useEffect, useLayoutEffect, useState } from 'react';
import { Check } from 'lucide-react';
import { FunnelFrame } from '@/components/funnel/FunnelFrame';
import { addressName } from '@/lib/funnel-personalization';
import { readFunnelState, saveFunnelState, trackFunnel, type FunnelPlan } from '@/lib/funnel';
import { checkoutForPlan } from '@/lib/hotmart-checkout';
export default function PlansPage() {
  const [plan, setPlan] = useState<FunnelPlan>('monthly');
  const [preferredName, setPreferredName] = useState('');
  useLayoutEffect(() => { window.scrollTo({ top: 0, left: 0, behavior: 'auto' }); document.documentElement.scrollTop = 0; document.body.scrollTop = 0; }, []);
  useEffect(() => { const state = readFunnelState(); if (state.plan) setPlan(state.plan); setPreferredName(state.preferredNameConfirmed === true ? addressName(state.preferredName) : ''); trackFunnel('pricing_viewed'); trackFunnel('plan_viewed'); trackFunnel('plans_viewed'); }, []);
  function select(value: FunnelPlan) { setPlan(value); saveFunnelState({ plan: value }); trackFunnel('plan_selected', { plan: value }); }
  return <FunnelFrame><section className="funnel-screen plans-screen"><div className="funnel-content narrow"><h1>{preferredName ? <><span className="plans-name">Ahora tengo una muy buena noticia para ti, {preferredName}.</span></> : 'Ahora tengo una muy buena noticia para ti.'}</h1><p className="plans-payoff">Todo lo que acabas de imaginar puede empezar a ser tuyo.</p><p className="funnel-copy">Ya viste cómo sería que NIA te escribiera a ti, recordara lo que estás trabajando y llegara justo a esos momentos en los que normalmente vuelves a dudar.</p><p className="plans-experience"><strong>Ahora puedes vivirlo con tus propios temas, tus propios momentos y mensajes pensados para ti.</strong></p><p className="trial-line">Tus primeros 7 días son gratis.</p><p className="plans-after-trial">Pruébalo. Vive la experiencia. Y después decides si quieres continuar.</p><div className="plans-grid"><button type="button" onClick={() => select('annual')} aria-pressed={plan === 'annual'} className={'plan-card plan-card-annual ' + (plan === 'annual' ? 'selected' : '')}><span className="plan-top"><span><strong>Anual</strong><small>Para hacer de NIA parte de tu proceso.</small></span><span className="plan-check">{plan === 'annual' && <Check size={14} />}</span></span><span className="plan-price">US$49.99<small>/ año</small></span><span className="plan-detail">7 días gratis. Después, US$49.99 al año.</span></button><button type="button" onClick={() => select('monthly')} aria-pressed={plan === 'monthly'} className={'plan-card ' + (plan === 'monthly' ? 'selected' : '')}><span className="plan-top"><span><strong>Mensual</strong><small>Más flexibilidad.</small></span><span className="plan-check">{plan === 'monthly' && <Check size={14} />}</span></span><span className="plan-price"><del>US$6.99</del><strong>US$4.99<small>/ mes</small></strong></span><span className="plan-detail">7 días gratis. Después, US$4.99 al mes.</span></button></div><p className="billing-note"><strong>Hoy no pagas nada.</strong><br />Si decides que NIA no es para ti, puedes cancelar antes de que terminen tus 7 días gratis.</p><button className="funnel-button full" onClick={() => { saveFunnelState({ plan }); const checkout = checkoutForPlan(plan); trackFunnel('checkout_started', { plan, price: checkout.price, provider: 'hotmart' }); window.location.assign(checkout.url); }}>Quiero empezar mis 7 días con NIA →</button></div></section></FunnelFrame>;
}
