/* eslint-disable react-hooks/set-state-in-effect -- hydrate local preview state after the browser is available. */
'use client';

import { useEffect, useState } from 'react';
import Link from 'next/link';
import { ArrowLeft } from 'lucide-react';
import { MvpShell } from '@/components/app/MvpShell';
import { defaultMvpState, readMvpState, type MvpState } from '@/lib/mvp';

export default function EvidencePage() { const [state, setState] = useState<MvpState>(defaultMvpState); useEffect(() => setState(readMvpState()), []); return <MvpShell title="Evidencia"><section className="pt-10"><Link href="/app" className="inline-flex items-center gap-2 text-[13px] text-[var(--text-tertiary)]"><ArrowLeft size={15} />Volver a Hoy</Link><p className="mt-12 text-[11px] font-bold uppercase tracking-[0.16em] text-[var(--accent)]">EVIDENCIA</p><h1 className="mt-5 text-[clamp(39px,7vw,76px)] font-semibold leading-[0.94] tracking-[-0.06em] [font-family:var(--font-display)]">{state.firstName || 'Laura'}, esto es lo que has ido reconociendo.</h1>{state.evidence.length === 0 ? <div className="mt-16 max-w-[540px] border-l-2 border-[var(--accent)] pl-5"><p className="text-[25px] leading-[1.1] [font-family:var(--font-display)]">Todavía no has guardado ningún momento.</p><p className="mt-4 text-[15px] leading-[1.6] text-[var(--text-secondary)]">No tienes que demostrar nada. Cuando reconozcas algo que quieras recordar, puedes guardarlo aquí.</p><Link href="/app" className="mt-7 inline-flex text-[14px] font-semibold text-[var(--accent)]">Reconocí un momento →</Link></div> : <div className="mt-14"><p className="text-[11px] font-bold uppercase tracking-[0.16em] text-[var(--accent)]">ESTA SEMANA</p><p className="mt-3 text-[34px] [font-family:var(--font-display)]">{state.evidence.length} momento{state.evidence.length === 1 ? '' : 's'}</p><div className="mt-10 space-y-5">{state.evidence.map((entry) => <article key={entry.id} className="border-t border-[color-mix(in_oklab,var(--text-primary)_15%,transparent)] pt-5"><p className="text-[11px] uppercase tracking-[0.14em] text-[var(--text-tertiary)]">{entry.date} · {entry.context}</p><p className="mt-3 text-[22px] [font-family:var(--font-display)]">{entry.text}</p></article>)}</div></div>}</section></MvpShell>; }
