'use client';

import Link from 'next/link';
import { ArrowLeft, CalendarDays, ChevronDown, Database, MessageCircle, Sparkles } from 'lucide-react';
import { useEffect, useState } from 'react';
import { AdminHeader, EmptyState, ErrorState, LoadingState, MetricCard, SectionHeading, StatusBadge } from '../../ui';
import QaRealControl from '../../qa-real-control';

type Row = Record<string, string | number | null>;
type Cost = { status: string; reason?: string; today?: number; sevenDays?: number; thirtyDays?: number; lifetime?: number; averagePerExecution?: number | null; averagePerIntervention?: number | null; byOperation?: { operation: string; total_cost: number; calls: number }[] };
type Payload = { user: { id: string; email: string | null; created_at: string; last_sign_in_at: string | null }; profile: Row | null; current_state: { desired_change: string | null; desired_change_since: string | null; context: string | null; context_since: string | null; learning_profile: unknown }; editorial_memory: { topics: { topic: string; count: number; last_seen: string; state: string; angles: { angle: string; count: number }[] }[]; formats: Record<string, number>; depths: Record<string, number>; rhythm: { dominantExperience: string | null; experienceConcentration: number; repeatedTake: string | null; repeatedTerritory: string | null; experienceCounts: Record<string, number>; last3: { topic: string | null; editorial_take?: string | null; experience_type?: string | null }[] } }; history: { contexts: Row[]; desired_changes: Row[] }; usage: { executions: { total: number; successful: number; approved: number; noApproved: number; failed: number }; approvedInterventions: number; deliveredInterventions: number; totalGenerationAttempts: number; technicalRetries: number; qualityRetries: number; feedback: number; learningSignals: number; recalibrations: number }; timeline: { id: string; type: string; at: string; execution_id: string | null; entity_id: string | null; metadata: unknown }[]; interventions: Row[]; feedback: Row[]; learning: Row[]; executions: Row[]; provider_usage: { operation: string; provider: string; model: string; calls: number; input_tokens: number; output_tokens: number; total_tokens: number; latency: { average: number; min: number; max: number } | null; errors: number }[]; subscription: Row | null; onboarding: { status: string; reason: string }; whatsapp: { status: string; reason: string }; cost: Cost };

const date = (value: unknown) => typeof value === 'string' && value ? new Date(value).toLocaleString('en-GB', { dateStyle: 'medium', timeStyle: 'short' }) : 'NOT AVAILABLE';
const shortDate = (value: unknown) => typeof value === 'string' && value ? new Date(value).toLocaleDateString('en-GB', { dateStyle: 'medium' }) : 'NOT AVAILABLE';
const text = (value: unknown) => typeof value === 'string' && value ? value : 'NOT AVAILABLE';
const num = (value: unknown) => new Intl.NumberFormat('en-US').format(Number(value) || 0);
const money = (value: number | null | undefined) => value === null || value === undefined ? 'NOT AVAILABLE' : `$${value.toFixed(value > 0 && value < 0.01 ? 6 : 4)}`;
const title = (value: string) => value.replaceAll('_', ' ');

function DetailRow({ label, value }: { label: string; value: unknown }) { return <div><p className="text-[11px] font-semibold uppercase tracking-[.11em] text-[var(--text-tertiary)]">{label}</p><p className="mt-1 break-words text-[14px]">{text(value)}</p></div>; }
function TechnicalJson({ value }: { value: unknown }) { return <details className="mt-4 rounded-[12px] border border-black/10 bg-[var(--bg)] p-3"><summary className="flex cursor-pointer list-none items-center gap-2 text-[12px] font-semibold text-[var(--text-secondary)]"><ChevronDown size={14} /> Technical JSON</summary><pre className="mt-3 max-h-64 overflow-auto whitespace-pre-wrap break-words text-[11px] text-[var(--text-secondary)]">{JSON.stringify(value ?? {}, null, 2)}</pre></details>; }
function Timeline({ rows }: { rows: Payload['timeline'] }) { return rows.length ? <div className="space-y-1">{rows.map(row => <div key={row.id} className="flex gap-3 rounded-[12px] px-2 py-3 hover:bg-[var(--surface)]"><div className="mt-0.5 grid h-7 w-7 shrink-0 place-items-center rounded-[9px] bg-[var(--surface)]"><CalendarDays size={14} /></div><div className="min-w-0 flex-1"><p className="text-[13px] font-semibold capitalize">{title(row.type)}</p><p className="mt-1 text-[11px] text-[var(--text-tertiary)]">{date(row.at)}</p></div>{row.execution_id && <Link href={`/admin/operations?execution=${row.execution_id}`} className="self-center font-mono text-[10px] text-[var(--accent)]">execution ↗</Link>}</div>)}</div> : <EmptyState title="No timeline yet" detail="No hay actividad operacional registrada." />; }
function CostPanel({ cost }: { cost: Cost }) { return cost.status === 'available' ? <><div className="mt-4 grid grid-cols-2 gap-3 text-[13px]"><DetailRow label="Today" value={money(cost.today)} /><DetailRow label="7 days" value={money(cost.sevenDays)} /><DetailRow label="30 days" value={money(cost.thirtyDays)} /><DetailRow label="Lifetime" value={money(cost.lifetime)} /><DetailRow label="Average / execution" value={money(cost.averagePerExecution)} /><DetailRow label="Average / intervention" value={money(cost.averagePerIntervention)} /></div><div className="mt-4 border-t border-black/10 pt-3 text-[12px] text-[var(--text-secondary)]">{(cost.byOperation ?? []).map(item => <div key={item.operation} className="flex justify-between py-1"><span className="capitalize">{title(item.operation)}</span><span>{money(item.total_cost)}</span></div>)}</div></> : <><p className="mt-4 text-[14px] font-semibold">NOT AVAILABLE</p><p className="mt-2 text-[12px] text-[var(--text-secondary)]">{cost.reason}</p></>; }

export default function AdminUserDetailPage({ params }: { params: Promise<{ id: string }> }) {
  const [data, setData] = useState<Payload | null>(null); const [error, setError] = useState('');
  useEffect(() => { params.then(({ id }) => fetch(`/api/admin/users/${id}`).then(async response => { const body = await response.json(); if (!response.ok) throw new Error(body.error); return body as Payload; }).then(setData).catch(reason => setError(reason instanceof Error && reason.message === 'user_not_found' ? 'Este usuario no existe.' : 'No pudimos cargar este usuario.'))); }, [params]);
  if (error) return <ErrorState message={error} />;
  if (!data) return <LoadingState />;
  return <div>
    <Link href="/admin/users" className="mb-6 inline-flex items-center gap-2 text-[13px] font-semibold text-[var(--text-secondary)] hover:text-[var(--accent)]"><ArrowLeft size={15} /> Back to users</Link>
    <AdminHeader eyebrow="NIA Control / User detail" title={data.user.email || 'User detail'} description={`User ID ${data.user.id}`} />
    <div className="mb-8"><QaRealControl userId={data.user.id} userEmail={data.user.email} whatsappStatus={data.whatsapp.status === 'connected' ? 'connected' : 'not connected'} /></div>
    <div className="space-y-8">
      <div className="grid gap-8 xl:grid-cols-[.8fr_1.2fr]"><section className="rounded-[20px] border border-black/10 bg-[var(--surface)] p-5"><SectionHeading title="Identity" /><div className="grid gap-5 sm:grid-cols-2 xl:grid-cols-1"><DetailRow label="Email" value={data.user.email} /><DetailRow label="User ID" value={data.user.id} /><DetailRow label="Created" value={date(data.user.created_at)} /><DetailRow label="Last access" value={date(data.user.last_sign_in_at)} /><DetailRow label="Account status" value="Available" /></div></section><section><SectionHeading title="Current state" /><div className="grid gap-4 md:grid-cols-2"><div className="rounded-[16px] border border-[var(--accent)]/30 bg-[color-mix(in_oklab,var(--accent)_8%,var(--surface))] p-5"><p className="text-[11px] font-semibold uppercase tracking-[.12em] text-[var(--accent)]">Desired change</p><p className="mt-4 text-[20px] leading-7 [font-family:var(--font-display)]">{text(data.current_state.desired_change)}</p><p className="mt-3 text-[12px] text-[var(--text-secondary)]">Active since {shortDate(data.current_state.desired_change_since)}</p></div><div className="rounded-[16px] border border-black/10 bg-[var(--surface)] p-5"><p className="text-[11px] font-semibold uppercase tracking-[.12em] text-[var(--text-tertiary)]">Active context</p><p className="mt-4 text-[20px] leading-7 [font-family:var(--font-display)]">{text(data.current_state.context)}</p><p className="mt-3 text-[12px] text-[var(--text-secondary)]">Active since {shortDate(data.current_state.context_since)}</p></div></div><div className="mt-4 rounded-[16px] border border-black/10 bg-[var(--surface)] p-5"><SectionHeading title="Learning profile" /><div className="text-[14px] text-[var(--text-secondary)]">{data.current_state.learning_profile && typeof data.current_state.learning_profile === 'object' && Object.keys(data.current_state.learning_profile as object).length ? <div className="grid gap-3 sm:grid-cols-2">{Object.entries(data.current_state.learning_profile as Record<string, unknown>).slice(0, 8).map(([key, value]) => <div key={key}><p className="text-[11px] font-semibold uppercase tracking-[.1em] text-[var(--text-tertiary)]">{title(key)}</p><p className="mt-1 break-words">{typeof value === 'string' ? value : JSON.stringify(value)}</p></div>)}</div> : <span>NOT AVAILABLE</span>}{data.current_state.learning_profile !== null && <TechnicalJson value={data.current_state.learning_profile} />}</div></div></section></div>

      <section><SectionHeading title="Usage" /><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><MetricCard label="Executions" value={num(data.usage.executions.total)} note={`${num(data.usage.executions.successful)} successful`} /><MetricCard label="Approved" value={num(data.usage.approvedInterventions)} accent /><MetricCard label="Delivered" value={num(data.usage.deliveredInterventions)} /><MetricCard label="No approved" value={num(data.usage.executions.noApproved)} /><MetricCard label="Failed" value={num(data.usage.executions.failed)} /><MetricCard label="Generation attempts" value={num(data.usage.totalGenerationAttempts)} /><MetricCard label="Retries" value={num(data.usage.technicalRetries + data.usage.qualityRetries)} note={`${num(data.usage.technicalRetries)} technical · ${num(data.usage.qualityRetries)} quality`} /><MetricCard label="Feedback / learning" value={`${num(data.usage.feedback)} / ${num(data.usage.learningSignals)}`} note={`${num(data.usage.recalibrations)} recalibrations`} /></div></section>
      <section className="rounded-[20px] border border-black/10 bg-[var(--surface)] p-5"><SectionHeading title="Editorial map" /><div className="grid gap-6 lg:grid-cols-4"><div><h3 className="text-[13px] font-semibold">Topics</h3><div className="mt-3 space-y-2">{data.editorial_memory.topics.length ? data.editorial_memory.topics.map(item => <div key={item.topic} className="flex items-center justify-between gap-3 text-[13px]"><span className="truncate">{item.topic}</span><span className="shrink-0 text-[11px] text-[var(--text-secondary)]">{item.count} · {item.state}</span></div>) : <p className="text-[13px] text-[var(--text-secondary)]">Sin metadata editorial todavía.</p>}</div></div><div><h3 className="text-[13px] font-semibold">Formats</h3><div className="mt-3 space-y-2">{Object.entries(data.editorial_memory.formats).filter(([, count]) => count > 0).map(([key, count]) => <div key={key} className="flex justify-between text-[13px]"><span>{key.replaceAll('_', ' ')}</span><span>{count}</span></div>)}</div></div><div><h3 className="text-[13px] font-semibold">Depth</h3><div className="mt-3 space-y-2">{Object.entries(data.editorial_memory.depths).filter(([, count]) => count > 0).map(([key, count]) => <div key={key} className="flex justify-between text-[13px]"><span>{key}</span><span>{count}</span></div>)}</div></div><div><h3 className="text-[13px] font-semibold">Recent rhythm</h3><p className="mt-3 text-[13px]">{data.editorial_memory.rhythm.dominantExperience ? `${data.editorial_memory.rhythm.dominantExperience.replaceAll('_', ' ')} · ${Math.round(data.editorial_memory.rhythm.experienceConcentration * 100)}%` : 'Sin ritmo suficiente todavía.'}</p>{data.editorial_memory.rhythm.repeatedTake && <p className="mt-2 text-[12px] text-[var(--text-secondary)]">Take repetido: {data.editorial_memory.rhythm.repeatedTake}</p>}{data.editorial_memory.rhythm.last3.length > 0 && <div className="mt-3 space-y-2">{data.editorial_memory.rhythm.last3.map((item, index) => <div key={`${item.topic}-${index}`} className="text-[12px] text-[var(--text-secondary)]"><span className="font-semibold">{item.experience_type?.replaceAll('_', ' ') ?? 'legacy'}</span>{item.editorial_take ? ` · ${item.editorial_take}` : ''}</div>)}</div>}</div></div></section>

      <section className="rounded-[20px] border border-black/10 bg-[var(--bg)] p-5"><SectionHeading title="NIA timeline" /><Timeline rows={data.timeline} /></section>

      <section><SectionHeading title="Interventions" href="/admin/interventions" />{data.interventions.length ? <div className="overflow-hidden rounded-[16px] border border-black/10 bg-[var(--surface)]"><div className="overflow-x-auto"><table className="w-full min-w-[900px] text-left text-[13px]"><thead className="border-b border-black/10 bg-[var(--bg)] text-[10px] uppercase tracking-[.12em] text-[var(--text-tertiary)]"><tr><th className="px-4 py-3">Date</th><th className="px-4 py-3">Intervention</th><th className="px-4 py-3">Function</th><th className="px-4 py-3">Concept / angle</th><th className="px-4 py-3">Channel</th><th className="px-4 py-3">Status</th></tr></thead><tbody className="divide-y divide-black/10">{data.interventions.map(item => <tr key={String(item.id)} className="hover:bg-[var(--bg)]"><td className="whitespace-nowrap px-4 py-3 text-[12px] text-[var(--text-secondary)]">{date(item.created_at)}</td><td className="max-w-[330px] px-4 py-3"><Link href={`/admin/interventions/${item.id}`} className="block font-semibold hover:text-[var(--accent)]">{text(item.text)}</Link><span className="mt-1 block text-[11px] text-[var(--text-tertiary)]">{item.execution_id ? `Execution ${String(item.execution_id).slice(0, 8)}` : 'Execution unavailable'}</span></td><td className="px-4 py-3">{text(item.function)}</td><td className="max-w-[240px] px-4 py-3 text-[var(--text-secondary)]"><span className="block truncate">{text(item.concept)}</span><span className="mt-1 block truncate text-[12px]">{text(item.angle)}</span></td><td className="px-4 py-3 capitalize">{text(item.channel)}</td><td className="px-4 py-3"><StatusBadge value={String(item.status ?? 'unknown')} /></td></tr>)}</tbody></table></div></div> : <EmptyState title="No interventions yet" detail="Esta persona todavía no tiene intervenciones registradas." />}</section>

      <div className="grid gap-8 xl:grid-cols-2"><section><SectionHeading title="Feedback" />{data.feedback.length ? <div className="space-y-3">{data.feedback.map(item => <div key={String(item.id)} className="rounded-[16px] border border-black/10 bg-[var(--surface)] p-4"><div className="flex items-start justify-between gap-3"><p className="font-semibold">{text(item.dimension)}</p><span className="text-[11px] text-[var(--text-tertiary)]">{date(item.created_at)}</span></div><p className="mt-2 text-[13px] text-[var(--text-secondary)]">{text(item.selected_option)}</p>{item.intervention_id && <Link href={`/admin/interventions/${item.intervention_id}`} className="mt-3 inline-block text-[12px] font-semibold text-[var(--accent)]">Open intervention ↗</Link>}</div>)}</div> : <EmptyState title="No feedback yet" />}</section><section><SectionHeading title="Learning signals" />{data.learning.length ? <div className="space-y-3">{data.learning.map(item => <div key={String(item.id)} className="rounded-[16px] border border-black/10 bg-[var(--surface)] p-4"><div className="flex items-start justify-between gap-3"><p className="font-semibold">{title(String(item.signal))}</p><span className="text-[11px] text-[var(--text-tertiary)]">{date(item.created_at)}</span></div><p className="mt-2 break-words text-[13px] text-[var(--text-secondary)]">{typeof item.value === 'string' ? item.value : JSON.stringify(item.value)}</p><p className="mt-2 text-[11px] text-[var(--text-tertiary)]">{text(item.source)} · confidence {text(item.confidence)}</p></div>)}</div> : <EmptyState title="No learning signals yet" />}</section></div>

      <div className="grid gap-8 xl:grid-cols-[1.15fr_.85fr]"><section><SectionHeading title="Context history" />{data.history.contexts.length ? <div className="space-y-3">{data.history.contexts.map(item => <div key={String(item.id)} className="rounded-[14px] border border-black/10 bg-[var(--surface)] p-4"><div className="flex items-start justify-between gap-3"><p className="font-semibold">{text(item.context_original)}</p><StatusBadge value={item.status === 'active' ? 'approved' : 'previous'} /></div><p className="mt-2 text-[12px] text-[var(--text-secondary)]">{date(item.created_at)} · {text(item.source)}</p></div>)}</div> : <EmptyState title="No context history" />}</section><section><SectionHeading title="Desired change history" />{data.history.desired_changes.length ? <div className="space-y-3">{data.history.desired_changes.map(item => <div key={String(item.id)} className="rounded-[14px] border border-black/10 bg-[var(--surface)] p-4"><div className="flex items-start justify-between gap-3"><p className="font-semibold">{text(item.desired_change_original)}</p><StatusBadge value={item.status === 'active' ? 'approved' : 'previous'} /></div><p className="mt-2 text-[12px] text-[var(--text-secondary)]">{date(item.created_at)}</p></div>)}</div> : <EmptyState title="No desired change history" />}</section></div>

      <section><SectionHeading title="Executions" href="/admin/operations" />{data.executions.length ? <div className="overflow-hidden rounded-[16px] border border-black/10 bg-[var(--surface)]"><div className="overflow-x-auto"><table className="w-full min-w-[950px] text-left text-[13px]"><thead className="border-b border-black/10 bg-[var(--bg)] text-[10px] uppercase tracking-[.12em] text-[var(--text-tertiary)]"><tr><th className="px-4 py-3">Execution / request</th><th className="px-4 py-3">Channel / trigger</th><th className="px-4 py-3">Status</th><th className="px-4 py-3">Started</th><th className="px-4 py-3">Duration</th><th className="px-4 py-3">Candidates</th><th className="px-4 py-3">Retries</th><th className="px-4 py-3">Failure</th></tr></thead><tbody className="divide-y divide-black/10">{data.executions.map(item => <tr key={String(item.id)}><td className="px-4 py-3"><Link href={`/admin/operations?execution=${item.id}`} className="font-mono text-[11px] text-[var(--accent)]">{String(item.id).slice(0, 12)}…</Link><span className="mt-1 block font-mono text-[10px] text-[var(--text-tertiary)]">{String(item.request_id).slice(0, 12)}…</span></td><td className="px-4 py-3 text-[var(--text-secondary)]">{text(item.channel)} · {text(item.trigger_source)}</td><td className="px-4 py-3"><StatusBadge value={String(item.status)} /></td><td className="whitespace-nowrap px-4 py-3 text-[12px]">{date(item.started_at)}</td><td className="px-4 py-3">{item.duration_ms ? `${item.duration_ms} ms` : 'NOT AVAILABLE'}</td><td className="px-4 py-3">{num(item.candidate_count)}</td><td className="px-4 py-3">{num(item.retry_count)}</td><td className="px-4 py-3 text-[#813e31]">{text(item.failure_code)}</td></tr>)}</tbody></table></div></div> : <EmptyState title="No executions yet" />}</section>

      <section><SectionHeading title="AI usage" />{data.provider_usage.length ? <div className="overflow-hidden rounded-[16px] border border-black/10 bg-[var(--surface)]"><div className="overflow-x-auto"><table className="w-full min-w-[900px] text-left text-[13px]"><thead className="border-b border-black/10 bg-[var(--bg)] text-[10px] uppercase tracking-[.12em] text-[var(--text-tertiary)]"><tr><th className="px-4 py-3">Operation</th><th className="px-4 py-3">Provider / model</th><th className="px-4 py-3">Calls</th><th className="px-4 py-3">Input</th><th className="px-4 py-3">Output</th><th className="px-4 py-3">Total</th><th className="px-4 py-3">Latency</th><th className="px-4 py-3">Errors</th></tr></thead><tbody className="divide-y divide-black/10">{data.provider_usage.map(item => <tr key={`${item.operation}:${item.provider}:${item.model}`}><td className="px-4 py-3 font-semibold capitalize">{title(item.operation)}</td><td className="px-4 py-3">{item.provider}<span className="mt-1 block text-[11px] text-[var(--text-secondary)]">{item.model}</span></td><td className="px-4 py-3">{num(item.calls)}</td><td className="px-4 py-3">{num(item.input_tokens)}</td><td className="px-4 py-3">{num(item.output_tokens)}</td><td className="px-4 py-3">{num(item.total_tokens)}</td><td className="px-4 py-3">{item.latency ? `${item.latency.average} ms` : 'NOT AVAILABLE'}</td><td className="px-4 py-3 text-[#813e31]">{num(item.errors)}</td></tr>)}</tbody></table></div></div> : <EmptyState title="No provider usage yet" detail="No hay llamadas de proveedor asociadas a este usuario." />}</section>

      <div className="grid gap-4 md:grid-cols-3"><section className="rounded-[16px] border border-black/10 bg-[var(--surface)] p-5"><div className="flex items-center gap-2 text-[var(--text-secondary)]"><Sparkles size={15} /><h2 className="text-[13px] font-semibold">Subscription</h2></div>{data.subscription ? <div className="mt-4 space-y-2 text-[13px]"><DetailRow label="Status" value={data.subscription.status} /><DetailRow label="Plan" value={data.subscription.plan_key} /><DetailRow label="Created" value={date(data.subscription.created_at)} /><DetailRow label="Current period" value={date(data.subscription.current_period_end)} /></div> : <p className="mt-4 text-[13px] text-[var(--text-secondary)]">NOT AVAILABLE</p>}</section><section className="rounded-[16px] border border-black/10 bg-[var(--surface)] p-5"><div className="flex items-center gap-2 text-[var(--text-secondary)]"><MessageCircle size={15} /><h2 className="text-[13px] font-semibold">WhatsApp</h2></div><p className="mt-4 text-[14px] font-semibold">{data.whatsapp.status}</p><p className="mt-2 text-[12px] text-[var(--text-secondary)]">{data.whatsapp.reason}</p></section><section className="rounded-[16px] border border-black/10 bg-[var(--surface)] p-5"><div className="flex items-center gap-2 text-[var(--text-secondary)]"><Database size={15} /><h2 className="text-[13px] font-semibold">Cost</h2></div><CostPanel cost={data.cost} /></section></div>

      <section className="rounded-[16px] border border-black/10 bg-[var(--surface)] p-5"><SectionHeading title="Onboarding" /><p className="text-[14px] font-semibold">{data.onboarding.status}</p><p className="mt-2 text-[12px] text-[var(--text-secondary)]">{data.onboarding.reason}</p></section>
    </div>
  </div>;
}
