import fs from 'node:fs/promises';
import path from 'node:path';

const root=path.resolve(process.env.REDTEAM_OUTPUT_DIR||'output/red-team');
async function jsonl(file){return (await fs.readFile(path.join(root,file),'utf8')).split('\n').filter(Boolean).map(line=>JSON.parse(line));}
const stories=await jsonl('stories.jsonl'); const candidates=await jsonl('candidates.jsonl');
const storyById=new Map(stories.map(x=>[x.story_id,x]));
const byStory=new Map(); for(const c of candidates){if(!byStory.has(c.story_id))byStory.set(c.story_id,[]);byStory.get(c.story_id).push(c);}
const reasonCounts=new Map();for(const c of candidates)for(const reason of c.all_rejection_reasons||[])reasonCounts.set(reason,(reasonCounts.get(reason)||0)+1);
const llmGroups=new Map();for(const c of candidates.filter(x=>x.primary_rejection_layer==='llm'))for(const reason of c.audit_results?.llm?.reasons||[]){const r=/coach|instrucc|reflex|revisa|céntrate|aconse|consejo/i.test(reason)?'coaching':/chatbot|asistente|recuerda que|es importante/i.test(reason)?'chatbot':/general|especific|obvi/i.test(reason)?'generality':/context|pareja|familia|jefe|supone|asume/i.test(reason)?'unsupported_context':/repet|idea reciente|ángulo/i.test(reason)?'repetition':'other';llmGroups.set(r,(llmGroups.get(r)||0)+1);}
const rounds={};for(const s of stories){const r=rounds[s.round]??={stories:0,approved:0,no_approved:0,candidates:0,deterministic:0,semantic:0,llm:0,duplicates:0};r.stories++;if(s.final_status==='approved')r.approved++;if(s.final_status==='no_approved_intervention')r.no_approved++;for(const c of byStory.get(s.story_id)||[]){r.candidates++;if(c.primary_rejection_layer==='deterministic')r.deterministic++;if(c.primary_rejection_layer==='semantic')r.semantic++;if(c.primary_rejection_layer==='llm')r.llm++;if(c.semantic_duplicate)r.duplicates++;}}
const table=stories.map(s=>{const prior=s.brief?.recentInterventions?.at(-1)||'';const selected=s.selected_intervention||'';const c=(byStory.get(s.story_id)||[]).find(x=>x.text===selected);return {story_id:s.story_id,person_id:s.person_id,round:s.round,desired_change:s.desired_change,context:s.active_context,previous_intervention:prior,feedback:s.feedback||null,learning_signal:(s.learning_signals||[]).length?s.learning_signals:null,concept:c?.concept||null,angle:c?.angle||null,final_status:s.final_status};});
const csv=v=>`"${String(v??'').replaceAll('"','""')}"`;
const semanticDuplicates=candidates.filter(x=>x.semantic_duplicate);const semanticReview=candidates.filter(x=>x.primary_rejection_layer==='semantic'&&!x.semantic_duplicate);
const semanticCases=candidates.filter(x=>x.primary_rejection_layer==='semantic').map(c=>{const s=storyById.get(c.story_id);const brief=s?.brief||{};const semantic=c.audit_results?.semantic||{};const sim=Number.isFinite(semantic.similarity)?semantic.similarity:null;const status=c.semantic_duplicate?'duplicate':semantic.semanticStatus==='review'?'review':semantic.semanticStatus||'review';return {case_id:c.candidate_id,person_id:c.person_id,story_id:c.story_id,round:c.round,previous_intervention:brief.recentInterventions?.at(-1)||'',candidate_text:c.text,similarity:sim,previous_concept:brief.recentConcepts?.at(-1)||'',candidate_concept:c.concept||'',previous_angle:brief.recentAngles?.at(-1)||'',candidate_angle:c.angle||'',previous_structure:brief.recentStructures?.at(-1)||'',candidate_structure:c.structure||'',semantic_status:status,primary_rejection_layer:c.primary_rejection_layer,all_rejection_reasons:c.all_rejection_reasons||[],semantic_warnings:semantic.warnings||[]};}).sort((a,b)=>{const rank=x=>x.semantic_status==='duplicate'?0:1;return rank(a)-rank(b)||(b.similarity??-1)-(a.similarity??-1);});
const semanticSimilarities=semanticCases.map(x=>x.similarity).filter(x=>x!==null).sort((a,b)=>a-b);const median=xs=>xs.length?xs.length%2?xs[(xs.length-1)/2]:(xs[xs.length/2-1]+xs[xs.length/2])/2:null;const rangeCounts={'0.90–1.00':0,'0.80–0.89':0,'0.70–0.79':0,'0.60–0.69':0,'0.50–0.59':0,'<0.50':0};for(const x of semanticSimilarities){if(x>=.9)rangeCounts['0.90–1.00']++;else if(x>=.8)rangeCounts['0.80–0.89']++;else if(x>=.7)rangeCounts['0.70–0.79']++;else if(x>=.6)rangeCounts['0.60–0.69']++;else if(x>=.5)rangeCounts['0.50–0.59']++;else rangeCounts['<0.50']++;}
const semanticHeader=['case_id','person_id','story_id','round','previous_intervention','candidate_text','similarity','previous_concept','candidate_concept','previous_angle','candidate_angle','previous_structure','candidate_structure','semantic_status','primary_rejection_layer','all_rejection_reasons'];const semanticCsv=[semanticHeader.join(',')];for(const x of semanticCases)semanticCsv.push([x.case_id,x.person_id,x.story_id,x.round,x.previous_intervention,x.candidate_text,x.similarity,x.previous_concept,x.candidate_concept,x.previous_angle,x.candidate_angle,x.previous_structure,x.candidate_structure,x.semantic_status,x.primary_rejection_layer,x.all_rejection_reasons.join('; ')].map(csv).join(','));await fs.writeFile(path.join(root,'semantic-calibration.csv'),`${semanticCsv.join('\n')}\n`);
const semanticMd=['# Semantic calibration','',`Total semantic cases: ${semanticCases.length}`,`Semantic duplicate: ${semanticCases.filter(x=>x.semantic_status==='duplicate').length}`,`Semantic review: ${semanticCases.filter(x=>x.semantic_status==='review').length}`,''];for(const [i,x] of semanticCases.entries()){const reason=[...x.all_rejection_reasons,...x.semantic_warnings].filter(Boolean).join('; ')||'No registrada';semanticMd.push(`### Caso ${i+1}`,`Round: ${x.round}`,`Similarity: ${x.similarity??'No disponible'}`,`Intervención anterior: ${x.previous_intervention}`,`Candidata: ${x.candidate_text}`,`Concept anterior: ${x.previous_concept}`,`Concept nuevo: ${x.candidate_concept}`,`Angle anterior: ${x.previous_angle}`,`Angle nuevo: ${x.candidate_angle}`,`Structure anterior: ${x.previous_structure}`,`Structure nueva: ${x.candidate_structure}`,`Resultado automático: ${x.semantic_status}`,`Razón: ${reason}`,'','[ ] DUPLICATE','[ ] SAME THEME / DIFFERENT ANGLE','[ ] DISTINCT','', '1. ¿La nueva intervención expresa esencialmente la misma idea que la anterior?','2. ¿La nueva intervención propone o expresa el mismo ángulo?','3. ¿La nueva intervención aporta una observación diferente?','4. ¿Una persona podría sentir que recibió básicamente el mismo mensaje otra vez?','','---','');}semanticMd.push('## Resumen','',`Total semantic cases: ${semanticCases.length}`,`Semantic duplicate: ${semanticCases.filter(x=>x.semantic_status==='duplicate').length}`,`Semantic review: ${semanticCases.filter(x=>x.semantic_status==='review').length}`,`Similarity mínima: ${semanticSimilarities.length?semanticSimilarities[0]:'No disponible'}`,`Similarity máxima: ${semanticSimilarities.length?semanticSimilarities.at(-1):'No disponible'}`,`Similarity mediana: ${median(semanticSimilarities)??'No disponible'}`,'','Distribución por rangos','',...Object.entries(rangeCounts).map(([label,count])=>`${label}: ${count}`),'');await fs.writeFile(path.join(root,'semantic-calibration.md'),`${semanticMd.join('\n')}\n`);
const failedRound2=stories.filter(x=>x.round===2&&x.final_status==='no_approved_intervention');
const approvedR1=candidates.filter(x=>x.round===1&&x.final_result==='APPROVED').slice(0,5);const approvedR2=candidates.filter(x=>x.round===2&&x.final_result==='APPROVED').slice(0,5);const failedR2=failedRound2.flatMap(s=>byStory.get(s.story_id)||[]).slice(0,15);
function priority(c){if(c.round===2&&c.final_result==='REJECTED')return 'HIGH';if(c.primary_rejection_layer==='semantic'&&(c.audit_results?.semantic?.similarity||0)>=0.55)return 'HIGH';if(c.final_result==='APPROVED'&&c.round===2)return 'HIGH';if(c.primary_rejection_layer&&c.audit_results?.deterministic?.approved!==c.audit_results?.semantic?.approved)return 'HIGH';return c.final_result==='APPROVED'?'MEDIUM':'LOW';}
const reviewPool=[];const add=(rows,n)=>{let added=0;for(const c of rows){if(added>=n)break;if(!reviewPool.some(x=>x.candidate_id===c.candidate_id)){reviewPool.push(c);added++;}}};
add(candidates.filter(x=>x.final_result==='APPROVED'&&x.round===1),10);add(candidates.filter(x=>x.primary_rejection_layer==='semantic').sort((a,b)=>(Math.abs((a.audit_results?.semantic?.similarity||0)-0.58)-Math.abs((b.audit_results?.semantic?.similarity||0)-0.58))),10);add(candidates.filter(x=>x.primary_rejection_layer==='deterministic'),5);add(candidates.filter(x=>x.primary_rejection_layer==='llm'),5);
const header=['review_id','person_id','story_id','candidate_id','context','desired_change','candidate_text','function','concept','angle','structure','deterministic_result','semantic_result','llm_result','final_result','rejection_reason','review_priority','human_verdict','relevant','specific','natural','original','non_coaching','non_chatbot','useful','one_idea'];
const csvLines=[header.join(',')];for(const c of candidates){const s=storyById.get(c.story_id);csvLines.push([c.candidate_id,c.person_id,c.story_id,c.candidate_id,s?.active_context,s?.desired_change,c.text,c.function,c.concept,c.angle,c.structure,c.deterministic_result,c.semantic_result,c.llm_result,c.final_result,(c.all_rejection_reasons||[]).join('; '),priority(c),'','','','','','','',''].map(csv).join(','));}
await fs.writeFile(path.join(root,'human-review.csv'),`${csvLines.join('\n')}\n`);
const questions='1. ¿La frase aporta algo específico a esta persona?\n2. ¿La frase se siente contextualizada?\n3. ¿Suena natural?\n4. ¿Suena a chatbot?\n5. ¿Suena a coaching?\n6. ¿Es demasiado obvia?\n7. ¿Es realmente distinta de la intervención anterior?\n8. ¿Tiene una sola idea?\n9. ¿Yo querría recibir esto por WhatsApp?';
const md=['# Human review — Red Team','',`Muestra preparada: ${reviewPool.length} candidatos. Las respuestas quedan deliberadamente vacías.`,`Nota: el checkpoint actual contiene ${stories.length} historias y no contiene feedback ni learning signals; no se puede atribuir causalidad al aprendizaje.`, ''];
for(const [i,c] of reviewPool.entries()){const s=storyById.get(c.story_id);md.push(`## Caso ${i+1}`,`Contexto: ${s?.active_context||''}`,`Desired change: ${s?.desired_change||''}`,`Feedback: ${s?.feedback||'No registrado en checkpoint'}`,`Intervención anterior: ${s?.brief?.recentInterventions?.at(-1)||'Ninguna'}`,`Candidato: ${c.text}`,`Concept: ${c.concept}`,`Angle: ${c.angle}`,`Automated result: ${c.final_result}`,`Rejection reason: ${(c.all_rejection_reasons||[]).join('; ')||'Ninguna'}`,`Similarity: ${c.audit_results?.semantic?.similarity??'No disponible'}`,'',questions,'','---','');}
await fs.writeFile(path.join(root,'human-review-30.md'),`${md.join('\n')}\n`);
const report={stories:table,rounds,rejectionReasons:Object.fromEntries([...reasonCounts].sort((a,b)=>b[1]-a[1])),llmReasons:Object.fromEntries(llmGroups),semanticDuplicates:semanticDuplicates.map(c=>({story_id:c.story_id,candidate:c.text,concept:c.concept,angle:c.angle,similarity:c.audit_results?.semantic?.similarity,reasons:c.all_rejection_reasons})),semanticReview:semanticReview.map(c=>({story_id:c.story_id,candidate:c.text,similarity:c.audit_results?.semantic?.similarity,reasons:c.all_rejection_reasons})),failedRound2:failedRound2.map(s=>({story_id:s.story_id,candidates:(byStory.get(s.story_id)||[]).map(c=>({text:c.text,concept:c.concept,angle:c.angle,structure:c.structure,deterministic:c.deterministic_result,deterministic_reasons:c.audit_results?.deterministic?.reasons,semantic:c.semantic_result,similarity:c.audit_results?.semantic?.similarity,semantic_reasons:c.audit_results?.semantic?.reasons,llm:c.llm_result,llm_reasons:c.audit_results?.llm?.reasons,final:c.final_result,primary:c.primary_rejection_layer}))})),sample:{approved_round1:approvedR1.map(x=>x.candidate_id),approved_round2:approvedR2.map(x=>x.candidate_id),failed_round2:failedR2.map(x=>x.candidate_id)},human_review_count:reviewPool.length};
await fs.writeFile(path.join(root,'analysis.json'),JSON.stringify(report,null,2));console.log(JSON.stringify({status:'PASS',stories:stories.length,candidates:candidates.length,rounds,rejectionReasons:Object.fromEntries(reasonCounts),llmReasons:Object.fromEntries(llmGroups),semanticDuplicates:semanticDuplicates.length,semanticReview:semanticReview.length,humanReview:reviewPool.length}));
