export const redTeamPersons = [
  ['person-001','limites','Quiero poner límites sin sentirme mala persona.','Con mi familia termino diciendo que sí aunque no quiera.','rich'],
  ['person-002','limites-trabajo','Quiero poner límites en el trabajo.','Me escriben fuera de horario y respondo aunque estoy agotada.','rich'],
  ['person-003','decisiones','Quiero confiar más en mis decisiones.','En el trabajo me cuesta defender decisiones cuando alguien las cuestiona.','enough'],
  ['person-004','aprobacion','Quiero dejar de depender tanto de la aprobación.','Cambio lo que pienso cuando alguien cercano no está de acuerdo.','enough'],
  ['person-005','procrastinacion','Quiero dejar de posponer mis proyectos.','Abro el documento y termino ordenando cosas antes de empezar.','rich'],
  ['person-006','exposicion','Quiero mostrar más mi trabajo.','Tengo un proyecto personal y no publico avances por miedo a que lo juzguen.','rich'],
  ['person-007','conversaciones','Quiero tener conversaciones difíciles sin evitarlas.','Necesito hablar con una amiga sobre algo que me molestó y llevo días aplazándolo.','rich'],
  ['person-008','decir-no','Quiero aprender a decir que no.','Acepto planes los fines de semana y después me arrepiento.','enough'],
  ['person-009','decepcionar','Quiero dejar de actuar solo para no decepcionar.','Con mi familia acepto encargos que no caben en mi semana.','rich'],
  ['person-010','actuar','Quiero actuar aunque no me sienta lista.','Tengo una idea de curso pero sigo cambiando detalles antes de ofrecerla.','rich'],
  ['person-011','comparacion','Quiero compararme menos.','Después de ver el trabajo de otras personas siento que lo mío está atrasado.','enough'],
  ['person-012','perfeccionismo','Quiero terminar sin revisar todo infinitamente.','Releo mis correos varias veces antes de enviarlos.','rich'],
  ['person-013','control','Quiero tolerar mejor no tener todo bajo control.','Me cuesta delegar porque imagino que algo saldrá mal si no lo reviso.','rich'],
  ['person-014','conflicto','Quiero dejar de evitar el conflicto.','Cuando alguien se molesta conmigo, retiro lo que dije aunque lo pensaba.','rich'],
  ['person-015','relaciones','Quiero estar más presente en mis relaciones.','Durante una cena con mi pareja sigo pensando en lo que debo resolver mañana.','rich'],
  ['person-016','trabajo','Quiero sentirme más clara en mi trabajo.','En reuniones tengo una propuesta, pero cambio de tema cuando llega mi turno.','rich'],
  ['person-017','proyectos','Quiero avanzar con un proyecto propio.','Tengo horarios libres pero los lleno con tareas pequeñas y no avanzo en la parte principal.','rich'],
  ['person-018','dinero','Quiero tomar decisiones de dinero con menos miedo.','Pospongo revisar mis gastos porque temo encontrar algo que no pueda resolver.','rich'],
  ['person-019','habitos','Quiero construir un hábito de movimiento.','Me propongo hacerlo por la mañana, pero si pierdo ese momento abandono todo el día.','rich'],
  ['person-020','identidad','Quiero vivir de una forma más coherente conmigo.','Digo que quiero escribir, pero mi semana se organiza alrededor de lo que otros necesitan.','rich'],
  ['person-021','etapa','Quiero adaptarme a una nueva etapa.','Desde que cambié de ciudad sigo organizando mis días como si todavía viviera allí.','rich'],
  ['person-022','minimo-trabajo','Quiero confiar más en mis decisiones.','Me pasa mucho en el trabajo.','minimal'],
  ['person-023','minimo-relaciones','Quiero comunicarme mejor.','Me pasa con mi pareja.','minimal'],
  ['person-024','minimo-proyecto','Quiero avanzar.','Con un proyecto personal.','minimal'],
  ['person-025','insuficiente','Quiero sentirme diferente.','','insufficient'],
  ['person-026','ambiguo','Quiero estar mejor.','A veces siento que debería cambiar algo, pero no sé exactamente qué.','ambiguous'],
  ['person-027','cambiante','Quiero confiar más en mis decisiones.','Al principio me pasaba en el trabajo; ahora la situación es distinta.','changing'],
  ['person-028','objetivo-cambiante','Quiero confiar más en mis decisiones.','En el trabajo me cuesta defenderlas.','desired-change-changing'],
  ['person-029','limites-amigos','Quiero poner límites sin perder vínculos.','Con mis amistades digo que sí a planes aunque necesito descansar.','enough'],
  ['person-030','miedo-conflicto','Quiero responder distinto cuando hay tensión.','Si alguien levanta la voz, intento cerrar la conversación cuanto antes.','enough'],
].map(([id, theme, desired_change, current_context, context_level]) => ({ id, theme, desired_change, current_context, context_level }));
