import assert from 'node:assert/strict';
import fs from 'node:fs';

const source = fs.readFileSync('components/funnel/PremiumDiscover.tsx', 'utf8');
const keys = ['recognition', 'reframe', 'evidence', 'personalize', 'demo', 'testimonials'];
const ctas = ['Quiero entender por qué me pasa', 'Muéstrame cómo sería diferente', 'Quiero verlo conmigo', 'Sí, quiero vivir esto', 'Quiero comenzar a vivir la experiencia'];
assert.equal((source.match(/key: '(recognition|reframe|evidence|personalize|demo|testimonials)'/g) ?? []).length, 6);
for (const key of keys) assert.ok(source.includes("key: '" + key + "'"));
for (const cta of ctas) assert.ok(source.includes(cta));
assert.match(source, /DISCOVER_SCREENS\.length/);
assert.match(source, /router\.push\('\/descubre\/planes'\)/);
assert.doesNotMatch(source, /138|19\.951|Harkin|Psychological Bulletin · 2016/);
assert.match(source, /\+40\.000/);
assert.match(source, /14\.321/);
assert.match(source, /Price, Holcomb y Payne/);
assert.match(source, /Johnson y Whisman/);
assert.match(source, /Hoy no necesitas encontrar la manera/);
assert.match(source, /¿Qué necesito decir para no salir de esa conversación sintiendo que otra vez me callé\?/);
assert.match(source, /role="progressbar"/);
assert.match(source, /aria-valuemax=\{5\}/);
assert.doesNotMatch(source, /cta: 'Seguir'/);
assert.doesNotMatch(source, /premium-screen-9|premium-screen-8|premium-screen-7/);
assert.match(source, /key: 'testimonials'/);
assert.match(source, /Quiero comenzar a vivir la experiencia/);
assert.match(source, /screen_key/);
assert.match(fs.readFileSync('app/descubre/planes/page.tsx', 'utf8'), /plans_viewed/);
assert.ok(fs.existsSync('app/api/funnel/events/route.ts'));
assert.ok(fs.existsSync('supabase/migrations/20261010120000_funnel_events.sql'));
console.log('short public funnel tests: PASS');
